sudo: required
services: 
  - docker

before_install:
  - docker build -t godfather0309/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -r CI=true godfather0309/react-test npm run test

after_success:
  - docker build -t godfather0309/multi-client ./client
  - docker build -t godfather0309/multi-nginx ./nginx
  - docker build -t godfather0309/multi-server ./server
  - docker build -t godfather0309/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push godfather0309/multi-client
  - docker push godfather0309/multi-nginx
  - docker push godfather0309/multi-server
  - docker push godfather0309/multi-worker


